# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - training-programs.md
 - members.md

footer: 'For any inquiries, email us at root@vx-engineering.org'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
